### ISSUE TITLE
v1.0 RoadMap

### ISSUE THREAD

**Issue by coolaj86** [BeyondCodeBootcamp/DuckDNS.sh#1]
- [x] Update with token via DuckDNS API (via dfea775f10fbbdb9ea0546ef2a05dee272fd4d10)
- [x] Check current IP address (via `ipify` in https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/0cf350def70f06886aed4c347366cd57b19486e6)
- [x] Store last known IP (via `dig` in https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/0cf350def70f06886aed4c347366cd57b19486e6)
- [x] Do some math to calc 5 min, wait, loop (via dfea775f10fbbdb9ea0546ef2a05dee272fd4d10)
- [x] `enable` subcommand to setup and install as a service (via https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/652e188e63ab4b1b48c78339539403879a4af6fe)
- [x] ~~`init`~~ `auth` subcommand to setup new subdomain (via https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/652e188e63ab4b1b48c78339539403879a4af6fe and https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/05b4bb0d9058054e6c6e67cb21450131e7953b9c)
