### ISSUE TITLE
v1.1 Roadmap

### ISSUE THREAD

**Issue by coolaj86** [BeyondCodeBootcamp/DuckDNS.sh#7]
- [x] consistently quiet `curl` with `-fsSL`, and use `--max-time 5.5` (via https://github.com/BeyondCodeBootcamp/DuckDNS.sh/commit/a2f4bdef6a767ea90768199a7812b169d226ba9a)
- [x] add `version` command and info (via https://github.com/BeyondCodeBootcamp/DuckDNS.sh/pull/10/commits/eef5ded6d6e5b949a3f1c7c61288b5474478a3b9)
- [x] set execute bit
- [ ] ~~some sort of shell header info (name, desc, author and such)~~ `duckdns.sh version`
- [x] Publish to Webi
